"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createTeacher } from "@/app/(dashboard)/dashboard/teachers/actions";
import { Button } from "@/components/ui/button";

export function TeachersManager({ teachers, candidates }: { teachers: { id: string; name: string; email: string; active: boolean; classCount: number }[]; candidates: { id: string; name: string; email: string }[] }) {
  const router = useRouter(); const [show, setShow] = useState(false); const [profileId, setProfileId] = useState(""); const [displayName, setDisplayName] = useState(""); const [error, setError] = useState<string>(); const [pending, start] = useTransition();
  function submit(event: React.FormEvent) { event.preventDefault(); setError(undefined); start(async () => { const result = await createTeacher({ profileId, displayName }); if (!result.success) setError(result.error); else { setShow(false); setProfileId(""); setDisplayName(""); router.refresh(); } }); }
  return <div className="space-y-5"><Button onClick={() => setShow((value) => !value)} type="button">{show ? "Cancelar" : "Asociar profesor"}</Button>{show ? <form className="grid gap-4 rounded-xl border bg-card p-5 sm:grid-cols-2" onSubmit={submit}><div><label className="text-sm font-medium" htmlFor="teacher-profile">Usuario con rol profesor</label><select className="mt-2 h-10 w-full rounded-lg border bg-background px-3 text-sm" id="teacher-profile" onChange={(event) => setProfileId(event.target.value)} value={profileId}><option value="">Selecciona un usuario</option>{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.email}</option>)}</select></div><div><label className="text-sm font-medium" htmlFor="teacher-name">Nombre visible</label><input className="mt-2 h-10 w-full rounded-lg border bg-background px-3 text-sm" id="teacher-name" onChange={(event) => setDisplayName(event.target.value)} value={displayName} /></div><div className="sm:col-span-2"><Button disabled={pending} type="submit">{pending ? "Guardando…" : "Crear profesor"}</Button></div></form> : null}{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}<div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b bg-muted/40 text-muted-foreground"><tr>{["Nombre", "Correo", "Estado", "Clases"].map((label) => <th className="px-4 py-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{teachers.map((teacher) => <tr className="border-b last:border-0" key={teacher.id}><td className="px-4 py-3">{teacher.name}</td><td className="px-4 py-3">{teacher.email}</td><td className="px-4 py-3">{teacher.active ? "Activo" : "Inactivo"}</td><td className="px-4 py-3">{teacher.classCount}</td></tr>)}</tbody></table>{teachers.length === 0 ? <p className="px-5 py-10 text-center text-sm text-muted-foreground">No hay profesores asociados todavía.</p> : null}</div></div>;
}
