import { notFound } from "next/navigation";

import { buildWhatsAppClassMessage } from "@/lib/classes/helpers";
import { ClassDetailPanel } from "@/components/classes/class-detail-panel";
import { AttendanceManager } from "@/components/classes/attendance-manager";
import { utcToBogotaInput } from "@/lib/cycles/dates";
import { requireUser } from "@/lib/auth/user";
import { createClient } from "@/lib/supabase/server";

export default async function ClassDetailPage({ params }: Readonly<{ params: Promise<{ classId: string }> }>) {
  const user = await requireUser(); const { classId } = await params; const supabase = await createClient();
  const { data: item, error } = await supabase.from("classes").select("*").eq("id", classId).maybeSingle(); if (error || !item) notFound();
  const [{ data: teacher }, { data: cycle }, { data: registrations }, { data: reminders }] = await Promise.all([supabase.from("teachers").select("display_name").eq("id", item.teacher_id).maybeSingle(), supabase.from("weekly_cycles").select("name").eq("id", item.cycle_id).maybeSingle(), supabase.from("registrations").select("id, student_id, status").eq("class_id", item.id).in("status", ["pending", "confirmed", "attended", "absent"]), supabase.from("class_reminders").select("id, reminder_type, status, attempts, last_error").eq("class_id", item.id).order("created_at")]);
  const studentIds = registrations?.map((registration) => registration.student_id) ?? [];
  const { data: students } = studentIds.length > 0 ? await supabase.from("students").select("id, full_name").in("id", studentIds).order("full_name") : { data: [] as { id: string; full_name: string }[] };
  const { data: studentGuardians } = studentIds.length > 0 ? await supabase.from("students").select("id, guardian_id").in("id", studentIds) : { data: [] as { id: string; guardian_id: string }[] };
  const guardianIds = studentGuardians?.map((student) => student.guardian_id) ?? []; const { data: guardians } = guardianIds.length > 0 ? await supabase.from("guardians").select("id, full_name").in("id", guardianIds) : { data: [] as { id: string; full_name: string }[] };
  const message = buildWhatsAppClassMessage({ title: item.title, teacherName: teacher?.display_name ?? "Profesor IPP", startsAt: item.starts_at });
  const attendance = (registrations ?? []).flatMap((registration) => { const student = students?.find((item) => item.id === registration.student_id); const guardianId = studentGuardians?.find((item) => item.id === registration.student_id)?.guardian_id; const guardian = guardians?.find((item) => item.id === guardianId); return student && guardian ? [{ registrationId: registration.id, studentName: student.full_name, guardianName: guardian.full_name, status: registration.status === "attended" || registration.status === "absent" ? registration.status : "pending" as const }] : []; });
  return <section className="space-y-5 rounded-xl border bg-card p-6"><h1 className="text-2xl font-bold">{item.title}</h1><p className="text-sm text-muted-foreground">Profesor: {teacher?.display_name ?? "No disponible"} · Ciclo: {cycle?.name ?? "No disponible"}</p><p className="text-sm">Estado: {item.status} · Capacidad: {students?.length ?? 0} / {item.capacity}</p>{item.meeting_url && user.role !== "contact_manager" ? <a className="text-primary underline" href={item.meeting_url} rel="noreferrer" target="_blank">Abrir enlace de videollamada</a> : null}<ClassDetailPanel classItem={{ id: item.id, status: item.status, title: item.title, description: item.description ?? "", cycleId: item.cycle_id, teacherId: item.teacher_id, startsAt: utcToBogotaInput(item.starts_at), endsAt: utcToBogotaInput(item.ends_at), capacity: item.capacity, meetingUrl: item.meeting_url ?? "" }} message={message} role={user.role} /><AttendanceManager canManage={user.role === "admin" || user.role === "teacher" || user.role === "contact_manager"} classId={item.id} entries={attendance} />{user.role !== "contact_manager" ? <section><h2 className="text-lg font-bold">Recordatorios</h2>{reminders?.length ? <ul className="mt-3 space-y-2">{reminders.map((reminder) => <li className="rounded-lg border p-3 text-sm" key={reminder.id}>{reminder.reminder_type} · <strong>{reminder.status}</strong>{reminder.attempts ? ` · intentos: ${reminder.attempts}` : ""}{reminder.last_error ? <p className="mt-1 text-destructive">{reminder.last_error}</p> : null}</li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">No hay recordatorios generados aún.</p>}</section> : null}</section>;
}
