import { notFound } from "next/navigation";

import { ClassDetailPanel } from "@/components/classes/class-detail-panel";
import { AttendanceManager } from "@/components/classes/attendance-manager";
import { MeetingLink } from "@/components/classes/meeting-link";
import { formatBogotaDateTime, utcToBogotaInput } from "@/lib/cycles/dates";
import { CLASS_STATUS_LABELS } from "@/lib/classes/constants";
import { requireUser } from "@/lib/auth/user";
import { createClient } from "@/lib/supabase/server";

export default async function ClassDetailPage({ params }: Readonly<{ params: Promise<{ classId: string }> }>) {
  const user = await requireUser(); const { classId } = await params; const supabase = await createClient();
  const { data: item, error } = await supabase.from("classes").select("*").eq("id", classId).maybeSingle(); if (error || !item) notFound();
  const [{ data: teacher }, { data: cycle }, { data: registrations }, { data: reminders }, { data: activeTeachers }, { data: activeCycles }] = await Promise.all([supabase.from("teachers").select("display_name").eq("id", item.teacher_id).maybeSingle(), supabase.from("weekly_cycles").select("name").eq("id", item.cycle_id).maybeSingle(), supabase.from("registrations").select("id, student_id, status").eq("class_id", item.id).in("status", ["pending", "confirmed", "attended", "absent"]), supabase.from("class_reminders").select("id, reminder_type, status, attempts, last_error").eq("class_id", item.id).order("created_at"), supabase.from("teachers").select("id, display_name").eq("active", true).order("display_name"), supabase.from("weekly_cycles").select("id, name, starts_at, ends_at").eq("status", "open").order("starts_at")]);
  const studentIds = registrations?.map((registration) => registration.student_id) ?? [];
  const { data: students } = studentIds.length > 0 ? await supabase.from("students").select("id, full_name").in("id", studentIds).order("full_name") : { data: [] as { id: string; full_name: string }[] };
  const { data: studentGuardians } = studentIds.length > 0 ? await supabase.from("students").select("id, guardian_id").in("id", studentIds) : { data: [] as { id: string; guardian_id: string }[] };
  const guardianIds = studentGuardians?.map((student) => student.guardian_id) ?? []; const { data: guardians } = guardianIds.length > 0 ? await supabase.from("guardians").select("id, full_name, phone").in("id", guardianIds) : { data: [] as { id: string; full_name: string | null; phone: string }[] };
  const attendance = (registrations ?? []).flatMap((registration) => { const student = students?.find((item) => item.id === registration.student_id); const guardianId = studentGuardians?.find((item) => item.id === registration.student_id)?.guardian_id; const guardian = guardians?.find((item) => item.id === guardianId); return student && guardian ? [{ registrationId: registration.id, studentName: student.full_name, guardianName: guardian.full_name ?? "Sin nombre", guardianPhone: guardian.phone }] : []; });
  return <section className="space-y-5 rounded-xl border bg-card p-6"><div><h1 className="text-2xl font-bold">{item.title}</h1><p className="mt-2 text-sm text-muted-foreground">Consulta la información y los inscritos de esta clase.</p></div><section className="rounded-xl border bg-muted/20 p-5"><h2 className="text-lg font-bold">Información de la clase</h2><dl className="mt-4 grid gap-x-8 gap-y-4 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Título</dt><dd className="mt-1 font-medium">{item.title}</dd></div><div><dt className="text-muted-foreground">Estado</dt><dd className="mt-1 font-medium">{CLASS_STATUS_LABELS[item.status]}</dd></div><div><dt className="text-muted-foreground">Profesor</dt><dd className="mt-1 font-medium">{teacher?.display_name ?? "No disponible"}</dd></div><div><dt className="text-muted-foreground">Ciclo</dt><dd className="mt-1 font-medium">{cycle?.name ?? "No disponible"}</dd></div><div><dt className="text-muted-foreground">Inicio</dt><dd className="mt-1 font-medium">{formatBogotaDateTime(item.starts_at)}</dd></div><div><dt className="text-muted-foreground">Fin</dt><dd className="mt-1 font-medium">{formatBogotaDateTime(item.ends_at)}</dd></div><div><dt className="text-muted-foreground">Cupo</dt><dd className="mt-1 font-medium">{students?.length ?? 0} / {item.capacity} estudiantes</dd></div>{item.description ? <div className="sm:col-span-2"><dt className="text-muted-foreground">Descripción</dt><dd className="mt-1 whitespace-pre-wrap font-medium">{item.description}</dd></div> : null}</dl></section>{item.meeting_url ? <MeetingLink url={item.meeting_url} /> : null}<ClassDetailPanel classItem={{ id: item.id, status: item.status, title: item.title, description: item.description ?? "", cycleId: item.cycle_id, teacherId: item.teacher_id, startsAt: utcToBogotaInput(item.starts_at), endsAt: utcToBogotaInput(item.ends_at), capacity: item.capacity, meetingUrl: item.meeting_url ?? "" }} cycles={(activeCycles ?? []).map((cycle) => ({ id: cycle.id, name: cycle.name, startsAt: cycle.starts_at, endsAt: cycle.ends_at }))} role={user.role} teachers={(activeTeachers ?? []).map((teacher) => ({ id: teacher.id, name: teacher.display_name }))} /><AttendanceManager entries={attendance} /><section><h2 className="text-lg font-bold">Recordatorios</h2>{reminders?.length ? <ul className="mt-3 space-y-2">{reminders.map((reminder) => <li className="rounded-lg border p-3 text-sm" key={reminder.id}>{reminder.reminder_type} · <strong>{reminder.status}</strong>{reminder.attempts ? ` · intentos: ${reminder.attempts}` : ""}{reminder.last_error ? <p className="mt-1 text-destructive">{reminder.last_error}</p> : null}</li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">No hay recordatorios generados aún.</p>}</section></section>;
}
