"use client";

import Link from "next/link";
import { CheckCircle2, ChevronLeft } from "lucide-react";
import { useState, useTransition } from "react";

import { confirmPublicClassSelections } from "@/app/clases/t/[token]/actions";
import { Button } from "@/components/ui/button";
import { formatBogotaDate, formatBogotaDateTime } from "@/lib/cycles/dates";

export interface PublicRegistrationClass { id: string; title: string; teacherName: string; startsAt: string; endsAt: string; capacity: number; registered: number; available: number; }
export interface PublicRegistrationStudent { id: string; fullName: string; registration: { title: string; teacherName: string; startsAt: string; endsAt: string } | null; }
const clock = (value: string) => formatBogotaDateTime(value).split(", ").at(-1) ?? "";

export function RegistrationFlow({ token, students, classes, canRegister }: Readonly<{ token: string; students: PublicRegistrationStudent[]; classes: PublicRegistrationClass[]; canRegister: boolean; }>) {
  const [selections, setSelections] = useState<Record<string, string>>({}); const [reviewing, setReviewing] = useState(false); const [complete, setComplete] = useState(false); const [error, setError] = useState<string>(); const [pending, startTransition] = useTransition();
  const selected = students.flatMap((student) => { const classItem = classes.find((item) => item.id === selections[student.id]); return classItem ? [{ student, classItem }] : []; });
  const selectedByOthers = (classId: string, studentId: string) => Object.entries(selections).filter(([selectedStudentId, selectedClassId]) => selectedStudentId !== studentId && selectedClassId === classId).length;
  function choose(studentId: string, classId: string) { setError(undefined); setSelections((current) => ({ ...current, [studentId]: classId })); }
  function confirm() { setError(undefined); startTransition(async () => { const result = await confirmPublicClassSelections(token, selected.map(({ student, classItem }) => ({ studentId: student.id, classId: classItem.id }))); if (!result.success) { setError(result.error); return; } setComplete(true); }); }
  if (complete) return <section className="rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><CheckCircle2 aria-hidden="true" className="mb-4 size-11 text-emerald-600" /><h2 className="text-3xl font-bold">¡Listo!</h2><p className="mt-3 text-lg leading-7 text-muted-foreground">Tus clases quedaron programadas.</p><div className="mt-6 space-y-3">{selected.map(({ student, classItem }) => <ClassSummary classItem={classItem} key={student.id} studentName={student.fullName} />)}</div><Button asChild className="mt-7 h-12 px-6 text-base"><Link href={`/clases/t/${token}`}>Ver mis clases</Link></Button></section>;
  if (reviewing) return <section className="rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><p className="text-base font-bold text-primary">PASO 3 DE 4</p><h2 className="mt-2 text-3xl font-bold">Confirma las clases</h2><p className="mt-3 text-lg leading-7 text-muted-foreground">Revisa que todo esté correcto antes de confirmar.</p><div className="mt-7 space-y-4">{selected.map(({ student, classItem }) => <ClassSummary classItem={classItem} key={student.id} studentName={student.fullName} />)}</div>{error ? <p className="mt-5 rounded-lg border border-destructive/30 p-4 text-base text-destructive" role="alert">{error}</p> : null}<div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row"><Button className="h-12 px-6 text-base" disabled={pending} onClick={() => setReviewing(false)} type="button" variant="outline"><ChevronLeft />Volver</Button><Button className="h-12 px-6 text-base" disabled={pending} onClick={confirm} type="button">{pending ? "Confirmando…" : "Confirmar clases"}</Button></div></section>;
  return <section className="space-y-7"><div><p className="text-base font-bold text-primary">PASOS 1 Y 2 DE 4</p><h2 className="mt-2 text-3xl font-bold">Escoge una clase para cada niño</h2><p className="mt-3 text-lg leading-7 text-muted-foreground">Puedes dejar a un niño sin clase esta semana.</p></div>{students.map((student) => <article className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6" key={student.id}><h3 className="text-2xl font-bold">{student.fullName}</h3>{student.registration ? <div className="mt-4 rounded-xl bg-emerald-50 p-4 text-base text-emerald-950"><strong>✓ Ya tiene una clase programada.</strong><br />{formatBogotaDateTime(student.registration.startsAt)} · {student.registration.teacherName}</div> : <div className="mt-5 grid gap-3">{classes.length === 0 ? <p className="text-lg text-muted-foreground">No hay clases disponibles esta semana.</p> : classes.map((classItem) => { const selectedHere = selections[student.id] === classItem.id; const noCapacity = classItem.available - selectedByOthers(classItem.id, student.id) <= 0 && !selectedHere; return <button aria-pressed={selectedHere} className={`rounded-xl border p-4 text-left transition-colors ${selectedHere ? "border-primary bg-secondary" : "bg-card hover:bg-muted"} disabled:cursor-not-allowed disabled:opacity-60`} disabled={!canRegister || noCapacity} key={classItem.id} onClick={() => choose(student.id, classItem.id)} type="button"><span className="block text-xl font-bold">{classItem.title}</span><span className="mt-1 block text-lg">Prof. {classItem.teacherName}</span><span className="mt-1 block text-base text-muted-foreground">{formatBogotaDate(classItem.startsAt)} · {clock(classItem.startsAt)} – {clock(classItem.endsAt)}</span><span className={`mt-3 block font-bold ${noCapacity ? "text-destructive" : "text-emerald-700"}`}>{noCapacity ? "Sin cupos" : `${Math.max(0, classItem.available - selectedByOthers(classItem.id, student.id))} cupos disponibles`}</span></button>; })}{selections[student.id] ? <Button className="h-11 self-start text-base" onClick={() => setSelections((current) => { const next = { ...current }; delete next[student.id]; return next; })} type="button" variant="outline">Dejar sin clase</Button> : null}</div>}</article>)}{error ? <p className="rounded-lg border border-destructive/30 p-4 text-base text-destructive" role="alert">{error}</p> : null}{canRegister ? <Button className="h-13 w-full text-lg sm:w-auto sm:px-8" disabled={selected.length === 0} onClick={() => setReviewing(true)} type="button">Revisar selección</Button> : null}</section>;
}

function ClassSummary({ studentName, classItem }: { studentName: string; classItem: Pick<PublicRegistrationClass, "title" | "teacherName" | "startsAt" | "endsAt"> }) { return <article className="rounded-xl border p-4"><h3 className="text-xl font-bold">{studentName}</h3><p className="mt-2 text-lg">{classItem.title}</p><p className="text-base text-muted-foreground">{formatBogotaDate(classItem.startsAt)}<br />{clock(classItem.startsAt)} – {clock(classItem.endsAt)}<br />Prof. {classItem.teacherName}</p></article>; }
