"use client";

import { flexRender, getCoreRowModel, getFilteredRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";
import Link from "next/link";
import { useState, useTransition } from "react";

import { addContactNote, assignContactManager, createTrackingInvitation, markFirstContact, markInvitationSent, recordWhatsAppOpened, updateContactResponse } from "@/app/(dashboard)/dashboard/tracking/actions";
import { Button } from "@/components/ui/button";
import { formatColombianPhone } from "@/lib/utils/phone";

export interface TrackingRow { guardianId: string; guardianName: string; phone: string; students: string[]; managerId: string | null; managerName: string | null; firstContactAt: string | null; invitationSentAt: string | null; response: string; booked: boolean; enrolledCount: number; nextClass: string | null; attendance: string; reminder: string; }
export interface ManagerOption { id: string; name: string; }
const responseLabel: Record<string, string> = { not_contacted: "Pendiente", contacted: "Contactado", no_response: "Sin respuesta", interested: "Interesado", declined: "No interesado", booked: "Agendado" };

export function TrackingManager({ rows, managers, isAdmin }: { rows: TrackingRow[]; managers: ManagerOption[]; isAdmin: boolean }) {
  const [filter, setFilter] = useState(""); const [response, setResponse] = useState("all"); const [error, setError] = useState<string>(); const [pending, startTransition] = useTransition();
  const visible = rows.filter((row) => (response === "all" || row.response === response || (response === "booked" && row.booked)) && `${row.guardianName} ${row.phone} ${row.students.join(" ")}`.toLowerCase().includes(filter.toLowerCase()));
  function execute(task: () => Promise<{ success: boolean; error?: string; message?: string }>) { setError(undefined); startTransition(async () => { const result = await task(); if (!result.success) setError(result.error ?? "No pudimos actualizar el seguimiento."); else if (result.message) { await navigator.clipboard.writeText(result.message); } }); }
  const columns: ColumnDef<TrackingRow>[] = [
    { accessorKey: "guardianName", header: "Acudiente", cell: ({ row }) => <div><strong>{row.original.guardianName}</strong><br /><span className="text-xs text-muted-foreground">{formatColombianPhone(row.original.phone)}</span></div> },
    { accessorKey: "students", header: "Niños", cell: ({ row }) => <span>{row.original.students.join(", ")}<br /><small>{row.original.enrolledCount} programados</small></span> },
    { accessorKey: "managerName", header: "Responsable", cell: ({ row }) => isAdmin ? <select aria-label={`Responsable de ${row.original.guardianName}`} defaultValue={row.original.managerId ?? ""} disabled={pending} onChange={(event) => execute(() => assignContactManager(row.original.guardianId, event.target.value || null))}><option value="">Sin responsable</option>{managers.map((manager) => <option key={manager.id} value={manager.id}>{manager.name}</option>)}</select> : row.original.managerName ?? "Sin responsable" },
    { accessorKey: "response", header: "Estado", cell: ({ row }) => <span>{row.original.booked ? "Agendado" : responseLabel[row.original.response] ?? row.original.response}</span> },
    { accessorKey: "nextClass", header: "Próxima clase", cell: ({ row }) => row.original.nextClass ?? "Sin clase" },
    { accessorKey: "attendance", header: "Asistencia", cell: ({ row }) => row.original.attendance },
    { accessorKey: "reminder", header: "Recordatorio", cell: ({ row }) => row.original.reminder },
    { id: "actions", header: "Acciones", cell: ({ row }) => <div className="flex flex-wrap gap-2"><Button asChild size="default" variant="outline"><a href={`https://wa.me/${row.original.phone.replace(/\D/g, "")}`} onClick={() => { void recordWhatsAppOpened(row.original.guardianId); }} rel="noreferrer" target="_blank">WhatsApp</a></Button><Button disabled={pending} onClick={() => execute(() => markFirstContact(row.original.guardianId))} type="button" variant="outline">Contactado</Button><Button disabled={pending} onClick={() => execute(() => markInvitationSent(row.original.guardianId))} type="button" variant="outline">Enviada</Button><select aria-label={`Respuesta de ${row.original.guardianName}`} defaultValue="" disabled={pending} onChange={(event) => { if (event.target.value) execute(() => updateContactResponse(row.original.guardianId, event.target.value as "no_response" | "interested" | "declined")); }}><option value="">Respuesta…</option><option value="no_response">Sin respuesta</option><option value="interested">Interesado</option><option value="declined">No interesado</option></select><Button disabled={pending} onClick={() => execute(() => createTrackingInvitation(row.original.guardianId, row.original.guardianName))} type="button" variant="outline">Generar invitación</Button><Button disabled={pending} onClick={() => { const note = window.prompt("Nota interna"); if (note) execute(() => addContactNote(row.original.guardianId, note)); }} type="button" variant="outline">Nota</Button><Button asChild variant="outline"><Link href={`/dashboard/contacts/${row.original.guardianId}`}>Ver</Link></Button></div> },
  ];
  // TanStack Table mutates its instance internally.
  // eslint-disable-next-line react-hooks/incompatible-library
  const table = useReactTable({ data: visible, columns, getCoreRowModel: getCoreRowModel(), getFilteredRowModel: getFilteredRowModel() });
  return <div className="space-y-4">{error ? <p className="rounded-lg border border-destructive/30 p-3 text-destructive" role="alert">{error}</p> : null}<div className="flex flex-wrap gap-3"><input aria-label="Buscar contacto" className="h-10 rounded-lg border bg-background px-3" onChange={(event) => setFilter(event.target.value)} placeholder="Buscar acudiente, teléfono o niño" value={filter} /><select aria-label="Filtrar por estado" onChange={(event) => setResponse(event.target.value)} value={response}><option value="all">Todos los estados</option><option value="not_contacted">Pendientes</option><option value="no_response">Sin respuesta</option><option value="interested">Interesados</option><option value="declined">No interesados</option><option value="booked">Agendados</option></select></div><div className="overflow-x-auto rounded-xl border bg-card"><table className="min-w-full text-sm"><thead className="bg-muted/50">{table.getHeaderGroups().map((group) => <tr key={group.id}>{group.headers.map((header) => <th className="p-3 text-left font-semibold" key={header.id}>{header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row) => <tr className="border-t align-top" key={row.id}>{row.getVisibleCells().map((cell) => <td className="p-3" key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div></div>;
}
