"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { useForm, type UseFormReturn } from "react-hook-form";

import { cancelClass, completeClass, createClass, publishClass } from "@/app/(dashboard)/dashboard/classes/actions";
import { Button } from "@/components/ui/button";
import { CLASS_STATUS_LABELS, type ClassStatus } from "@/lib/classes/constants";
import { getClassTemporalStatus } from "@/lib/classes/helpers";
import { formatBogotaDateTime, utcToBogotaInput } from "@/lib/cycles/dates";
import { classSchema, type ClassValues } from "@/lib/validations/classes";
import type { UserRole } from "@/types/user";

export interface ClassListItem { id: string; title: string; teacherId: string; teacherName: string; cycleId: string; cycleName: string; startsAt: string; endsAt: string; capacity: number; status: ClassStatus; }
export interface ClassTeacherOption { id: string; name: string; }
export interface ClassCycleOption { id: string; name: string; }

export function ClassesManager({ classes, teachers, cycles, role }: Readonly<{ classes: ClassListItem[]; teachers: ClassTeacherOption[]; cycles: ClassCycleOption[]; role: UserRole }>) {
  const router = useRouter(); const [showCreate, setShowCreate] = useState(false); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | ClassStatus>("all"); const [teacherFilter, setTeacherFilter] = useState("all"); const [cycleFilter, setCycleFilter] = useState("all"); const [dateFilter, setDateFilter] = useState(""); const [error, setError] = useState<string>(); const [isPending, startTransition] = useTransition();
  const form = useForm<ClassValues>({ resolver: zodResolver(classSchema), defaultValues: { capacity: 10, teacherId: role === "admin" ? "" : undefined, meetingUrl: "" } });
  const visible = classes.filter((item) => (status === "all" || item.status === status) && (teacherFilter === "all" || item.teacherId === teacherFilter) && (cycleFilter === "all" || item.cycleId === cycleFilter) && (!dateFilter || utcToBogotaInput(item.startsAt).startsWith(dateFilter)) && `${item.title} ${item.teacherName} ${item.cycleName}`.toLowerCase().includes(query.toLowerCase()));
  function create(values: ClassValues) { setError(undefined); startTransition(async () => { const result = await createClass(values); if (!result.success) { setError(result.error); return; } form.reset({ capacity: 10, teacherId: role === "admin" ? "" : undefined, meetingUrl: "" }); setShowCreate(false); if (result.classId) router.push(`/dashboard/classes/${result.classId}`); }); }
  function changeStatus(item: ClassListItem, action: "publish" | "cancel" | "complete") { const copy = { publish: `¿Publicar ${item.title}?`, cancel: `¿Cancelar ${item.title}? La clase se conservará en el historial.`, complete: `¿Marcar ${item.title} como finalizada?` }; if (!window.confirm(copy[action])) return; setError(undefined); startTransition(async () => { const result = action === "publish" ? await publishClass(item.id) : action === "cancel" ? await cancelClass(item.id) : await completeClass(item.id); if (!result.success) setError(result.error); else router.refresh(); }); }
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-3"><input aria-label="Buscar clases" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setQuery(event.target.value)} placeholder="Buscar clase o profesor" value={query} /><select aria-label="Filtrar por estado" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setStatus(event.target.value as typeof status)} value={status}><option value="all">Todos los estados</option>{Object.entries(CLASS_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar por profesor" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setTeacherFilter(event.target.value)} value={teacherFilter}><option value="all">Todos los profesores</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select><select aria-label="Filtrar por ciclo" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setCycleFilter(event.target.value)} value={cycleFilter}><option value="all">Todos los ciclos</option>{cycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{cycle.name}</option>)}</select><input aria-label="Filtrar por fecha" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setDateFilter(event.target.value)} type="date" value={dateFilter} /></div>{role !== "contact_manager" ? <Button onClick={() => setShowCreate((value) => !value)} type="button">{showCreate ? "Cancelar" : "Crear clase"}</Button> : null}</div>
    {showCreate ? <form className="grid gap-4 rounded-xl border bg-card p-5 sm:grid-cols-2" noValidate onSubmit={form.handleSubmit(create)}><Field form={form} id="class-title" label="Título" name="title" /><Field form={form} id="class-description" label="Descripción (opcional)" name="description" /><SelectField form={form} id="class-cycle" label="Ciclo" name="cycleId" options={cycles.map((cycle) => ({ value: cycle.id, label: cycle.name }))} />{role === "admin" ? <SelectField form={form} id="class-teacher" label="Profesor" name="teacherId" options={teachers.map((teacher) => ({ value: teacher.id, label: teacher.name }))} /> : null}<DateField form={form} id="class-start" label="Inicio (Bogotá)" name="startsAt" /><DateField form={form} id="class-end" label="Fin (Bogotá)" name="endsAt" /><Field form={form} id="class-capacity" label="Cupo máximo de niños" name="capacity" type="number" /><Field form={form} id="class-meeting" label="Enlace de videollamada (opcional)" name="meetingUrl" type="url" /><div className="sm:col-span-2"><Button disabled={isPending} type="submit">{isPending ? "Guardando…" : "Guardar borrador"}</Button></div></form> : null}
    {error ? <p className="rounded-lg border border-destructive/30 bg-card p-3 text-sm text-destructive" role="alert">{error}</p> : null}<div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[960px] text-left text-sm"><thead className="border-b bg-muted/40 text-muted-foreground"><tr>{["Clase", "Profesor", "Ciclo", "Horario", "Cupo", "Estado", "Acciones"].map((label) => <th className="px-4 py-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{visible.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="px-4 py-3 font-medium">{item.title}</td><td className="px-4 py-3">{item.teacherName}</td><td className="px-4 py-3">{item.cycleName}</td><td className="px-4 py-3">{formatBogotaDateTime(item.startsAt)} — {formatBogotaDateTime(item.endsAt)}</td><td className="px-4 py-3">0 / {item.capacity}</td><td className="px-4 py-3">{CLASS_STATUS_LABELS[item.status]} · {getClassTemporalStatus({ starts_at: item.startsAt, ends_at: item.endsAt, status: item.status })}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href={`/dashboard/classes/${item.id}`}>Ver</Link></Button>{role !== "contact_manager" && item.status === "draft" ? <Button onClick={() => changeStatus(item, "publish")} type="button">Publicar</Button> : null}{role !== "contact_manager" && item.status === "published" ? <><Button onClick={() => changeStatus(item, "cancel")} type="button" variant="outline">Cancelar</Button><Button onClick={() => changeStatus(item, "complete")} type="button" variant="outline">Finalizar</Button></> : null}</div></td></tr>)}</tbody></table>{visible.length === 0 ? <p className="px-5 py-10 text-center text-sm text-muted-foreground">No hay clases para mostrar.</p> : null}</div></div>;
}

type Form = UseFormReturn<ClassValues>;
function Field({ form, id, label, name, type = "text" }: { form: Form; id: string; label: string; name: keyof ClassValues; type?: string }) { const error = form.formState.errors[name]; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor={id}>{label}</label><input className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id={id} type={type} {...form.register(name, type === "number" ? { valueAsNumber: true } : undefined)} />{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
function DateField({ form, id, label, name }: { form: Form; id: string; label: string; name: "startsAt" | "endsAt" }) { return <Field form={form} id={id} label={label} name={name} type="datetime-local" />; }
function SelectField({ form, id, label, name, options }: { form: Form; id: string; label: string; name: "cycleId" | "teacherId"; options: { value: string; label: string }[] }) { const error = form.formState.errors[name]; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor={id}>{label}</label><select className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id={id} {...form.register(name)}><option value="">Selecciona una opción</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
