"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { Controller, useForm, useWatch, type UseFormReturn } from "react-hook-form";
import { Eye, Pencil, Plus, Trash2 } from "lucide-react";

import { createClass, deleteClass } from "@/app/(dashboard)/dashboard/classes/actions";
import { DateTimePicker } from "@/components/ui/date-time-picker";
import { Button } from "@/components/ui/button";
import { useConfirmation } from "@/components/ui/confirmation-dialog";
import { CLASS_STATUS_LABELS, type ClassStatus } from "@/lib/classes/constants";
import { getClassTemporalStatus } from "@/lib/classes/helpers";
import { formatBogotaDateTime, utcToBogotaInput } from "@/lib/cycles/dates";
import { classSchema, type ClassValues } from "@/lib/validations/classes";

export interface ClassListItem { id: string; title: string; teacherId: string; teacherName: string; cycleId: string; cycleName: string; startsAt: string; endsAt: string; capacity: number; registered: number; status: ClassStatus; }
export interface ClassTeacherOption { id: string; name: string; }
export interface ClassCycleOption { id: string; name: string; startsAt: string; endsAt: string; }

export function ClassesManager({ classes, teachers, cycles, canDelete }: Readonly<{ classes: ClassListItem[]; teachers: ClassTeacherOption[]; cycles: ClassCycleOption[]; canDelete: boolean }>) {
  const confirm = useConfirmation();
  const router = useRouter(); const [showCreate, setShowCreate] = useState(false); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | ClassStatus>("all"); const [teacherFilter, setTeacherFilter] = useState("all"); const [cycleFilter, setCycleFilter] = useState("all"); const [dateFilter, setDateFilter] = useState(""); const [error, setError] = useState<string>(); const [isPending, startTransition] = useTransition();
  const form = useForm<ClassValues>({ resolver: zodResolver(classSchema), defaultValues: { capacity: 4, teacherId: "", meetingUrl: "" } });
  const selectedCycleId = useWatch({ control: form.control, name: "cycleId" });
  const selectedCycle = cycles.find((cycle) => cycle.id === selectedCycleId);
  const filterTeachers = Array.from(new Map(classes.map((item) => [item.teacherId, { id: item.teacherId, name: item.teacherName }])).values());
  const filterCycles = Array.from(new Map(classes.map((item) => [item.cycleId, { id: item.cycleId, name: item.cycleName }])).values());
  const visible = classes.filter((item) => (status === "all" || item.status === status) && (teacherFilter === "all" || item.teacherId === teacherFilter) && (cycleFilter === "all" || item.cycleId === cycleFilter) && (!dateFilter || utcToBogotaInput(item.startsAt).startsWith(dateFilter)) && `${item.title} ${item.teacherName} ${item.cycleName}`.toLowerCase().includes(query.toLowerCase()));
  function create(values: ClassValues) { setError(undefined); startTransition(async () => { const result = await createClass(values); if (!result.success) { setError(result.error); return; } form.reset({ capacity: 4, teacherId: "", meetingUrl: "" }); setShowCreate(false); router.refresh(); }); }
  async function remove(item: ClassListItem) { if (!(await confirm({ title: "Eliminar clase", description: `Se eliminará la clase “${item.title}” y todas sus inscripciones.`, confirmLabel: "Eliminar clase" }))) return; setError(undefined); startTransition(async () => { const result = await deleteClass(item.id); if (!result.success) setError(result.error); else router.refresh(); }); }
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-3"><input aria-label="Buscar clases" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setQuery(event.target.value)} placeholder="Buscar clase o profesor" value={query} /><select aria-label="Filtrar por estado" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setStatus(event.target.value as typeof status)} value={status}><option value="all">Todos los estados</option>{Object.entries(CLASS_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar por profesor" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setTeacherFilter(event.target.value)} value={teacherFilter}><option value="all">Todos los profesores</option>{filterTeachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select><select aria-label="Filtrar por ciclo" className="h-10 rounded-lg border bg-card px-3 text-sm" onChange={(event) => setCycleFilter(event.target.value)} value={cycleFilter}><option value="all">Todos los ciclos</option>{filterCycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{cycle.name}</option>)}</select><DateTimePicker label="Filtrar por fecha" className="w-auto min-w-44" mode="date" onChange={setDateFilter} value={dateFilter} /></div><Button disabled={isPending || !teachers.length || !cycles.length} onClick={() => { setError(undefined); setShowCreate((value) => !value); }} type="button">{showCreate ? "Cancelar" : <><Plus aria-hidden="true" />Crear clase</>}</Button></div>
    {!teachers.length || !cycles.length ? <p className="rounded-lg border bg-card p-4 text-sm">Antes de crear una clase, prepara un <Link className="text-primary underline" href="/dashboard/cycles">ciclo activo</Link> y un <Link className="text-primary underline" href="/dashboard/teachers">profesor activo</Link>.</p> : null}
    {showCreate ? <form className="grid gap-4 rounded-xl border bg-card p-5 sm:grid-cols-2" noValidate onSubmit={form.handleSubmit(create)}><Field form={form} id="class-title" label="Título" name="title" /><Field form={form} id="class-description" label="Descripción (opcional)" name="description" /><SelectField form={form} id="class-cycle" label="Ciclo" name="cycleId" options={cycles.map((cycle) => ({ value: cycle.id, label: cycle.name }))} /><SelectField form={form} id="class-teacher" label="Profesor" name="teacherId" options={teachers.map((teacher) => ({ value: teacher.id, label: teacher.name }))} /><DateField form={form} id="class-start" label="Inicio (Bogotá)" max={selectedCycle ? utcToBogotaInput(selectedCycle.endsAt) : undefined} min={selectedCycle ? utcToBogotaInput(selectedCycle.startsAt) : undefined} name="startsAt" /><DateField form={form} id="class-end" label="Fin (Bogotá)" max={selectedCycle ? utcToBogotaInput(selectedCycle.endsAt) : undefined} min={selectedCycle ? utcToBogotaInput(selectedCycle.startsAt) : undefined} name="endsAt" />{selectedCycle ? <p className="text-sm text-muted-foreground sm:col-span-2">Horario permitido: {formatBogotaDateTime(selectedCycle.startsAt)} — {formatBogotaDateTime(selectedCycle.endsAt)}.</p> : <p className="text-sm text-muted-foreground sm:col-span-2">Selecciona un ciclo para habilitar el rango de fecha y hora.</p>}<Field form={form} id="class-capacity" label="Cupo máximo de niños" name="capacity" type="number" /><Field form={form} id="class-meeting" label="Enlace de videollamada" name="meetingUrl" required type="url" /><div className="sm:col-span-2"><Button disabled={isPending} type="submit">{isPending ? "Guardando…" : "Guardar clase activa"}</Button></div></form> : null}
    {error ? <p className="rounded-lg border border-destructive/30 bg-card p-3 text-sm text-destructive" role="alert">{error}</p> : null}<div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[960px] text-left text-sm"><thead className="border-b bg-muted/40 text-muted-foreground"><tr>{["Clase", "Profesor", "Ciclo", "Horario", "Cupo", "Estado", "Acciones"].map((label) => <th className="px-4 py-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{visible.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="px-4 py-3 font-medium">{item.title}</td><td className="px-4 py-3">{item.teacherName}</td><td className="px-4 py-3">{item.cycleName}</td><td className="px-4 py-3">{formatBogotaDateTime(item.startsAt)} — {formatBogotaDateTime(item.endsAt)}</td><td className="px-4 py-3">{item.registered} / {item.capacity}</td><td className="px-4 py-3">{CLASS_STATUS_LABELS[item.status]} · {getClassTemporalStatus({ starts_at: item.startsAt, ends_at: item.endsAt, status: item.status })}</td><td className="px-4 py-3"><div className="flex items-center gap-1.5"><Button asChild aria-label={`Ver ${item.title}`} size="icon" title="Ver clase" variant="outline"><Link href={`/dashboard/classes/${item.id}`}><Eye aria-hidden="true" /></Link></Button><Button asChild aria-label={`Editar ${item.title}`} size="icon" title="Editar clase" variant="outline"><Link href={`/dashboard/classes/${item.id}?edit=1`}><Pencil aria-hidden="true" /></Link></Button>{canDelete ? <Button aria-label={`Eliminar ${item.title}`} className="border border-transparent bg-transparent text-rose-500 hover:border-rose-100 hover:bg-rose-50 hover:text-rose-600" disabled={isPending} onClick={() => remove(item)} size="icon" title="Eliminar clase" type="button" variant="destructive"><Trash2 aria-hidden="true" /></Button> : null}</div></td></tr>)}</tbody></table>{visible.length === 0 ? <p className="px-5 py-10 text-center text-sm text-muted-foreground">No hay clases para mostrar.</p> : null}</div></div>;
}

type Form = UseFormReturn<ClassValues>;
function Field({ form, id, label, name, required = false, type = "text" }: { form: Form; id: string; label: string; name: keyof ClassValues; required?: boolean; type?: string }) { const error = form.formState.errors[name]; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor={id}>{label}{required ? " (obligatorio)" : null}</label><input className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id={id} required={required} type={type} {...form.register(name, type === "number" ? { valueAsNumber: true } : undefined)} />{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
function DateField({ form, id, label, max, min, name }: { form: Form; id: string; label: string; max?: string; min?: string; name: "startsAt" | "endsAt" }) { const error = form.formState.errors[name]; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor={id}>{label}</label><Controller control={form.control} name={name} render={({ field }) => <DateTimePicker {...field} id={id} label={label} max={max} min={min} invalid={Boolean(error)} />} />{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
function SelectField({ form, id, label, name, options }: { form: Form; id: string; label: string; name: "cycleId" | "teacherId"; options: { value: string; label: string }[] }) { const error = form.formState.errors[name]; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor={id}>{label}</label><select className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id={id} {...form.register(name)}><option value="">Selecciona una opción</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
