"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { useForm, useWatch, type UseFormReturn } from "react-hook-form";
import { Pencil, Trash2 } from "lucide-react";

import { deleteClass, updateClass } from "@/app/(dashboard)/dashboard/classes/actions";
import { Button } from "@/components/ui/button";
import { classSchema, type ClassValues } from "@/lib/validations/classes";
import { formatBogotaDateTime, utcToBogotaInput } from "@/lib/cycles/dates";
import type { UserRole } from "@/types/user";

export function ClassDetailPanel({ classItem, cycles, role, teachers }: { classItem: ClassValues & { id: string; status: string }; cycles: { id: string; name: string; startsAt: string; endsAt: string }[]; role: UserRole; teachers: { id: string; name: string }[] }) {
  const router = useRouter(); const [editing, setEditing] = useState(false); const [error, setError] = useState<string>(); const [pending, start] = useTransition(); const form = useForm<ClassValues>({ resolver: zodResolver(classSchema), defaultValues: classItem });
  const selectedCycleId = useWatch({ control: form.control, name: "cycleId" });
  const selectedCycle = cycles.find((cycle) => cycle.id === selectedCycleId);
  function submit(values: ClassValues) { setError(undefined); start(async () => { const result = await updateClass(classItem.id, values); if (!result.success) setError(result.error); else { setEditing(false); router.refresh(); } }); }
  function remove() { if (!window.confirm(`¿Eliminar permanentemente ${classItem.title} y sus inscripciones? Esta acción no se puede deshacer.`)) return; setError(undefined); start(async () => { const result = await deleteClass(classItem.id); if (!result.success) setError(result.error); else router.push("/dashboard/classes"); }); }
  return <div className="space-y-4"><div className="flex gap-2"><Button onClick={() => setEditing((value) => !value)} type="button" variant="outline">{editing ? "Cancelar edición" : <><Pencil aria-hidden="true" />Editar clase</>}</Button><Button className="border border-transparent bg-transparent text-rose-500 hover:border-rose-100 hover:bg-rose-50 hover:text-rose-600" disabled={pending} onClick={remove} type="button" variant="destructive"><Trash2 aria-hidden="true" />Eliminar clase</Button></div>{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}{editing ? <form className="grid gap-4 rounded-xl border p-4 sm:grid-cols-2" noValidate onSubmit={form.handleSubmit(submit)}><Input form={form} id="detail-title" label="Título" name="title" /><Input form={form} id="detail-description" label="Descripción" name="description" /><Input form={form} id="detail-meeting" label="Enlace HTTPS" name="meetingUrl" type="url" />{role === "admin" ? <><CycleSelect cycles={cycles} form={form} /><TeacherSelect form={form} teachers={teachers} /><DateInput form={form} id="detail-start" label="Inicio (Bogotá)" max={selectedCycle ? utcToBogotaInput(selectedCycle.endsAt) : undefined} min={selectedCycle ? utcToBogotaInput(selectedCycle.startsAt) : undefined} name="startsAt" /><DateInput form={form} id="detail-end" label="Fin (Bogotá)" max={selectedCycle ? utcToBogotaInput(selectedCycle.endsAt) : undefined} min={selectedCycle ? utcToBogotaInput(selectedCycle.startsAt) : undefined} name="endsAt" />{selectedCycle ? <p className="text-sm text-muted-foreground sm:col-span-2">Horario permitido: {formatBogotaDateTime(selectedCycle.startsAt)} — {formatBogotaDateTime(selectedCycle.endsAt)}.</p> : null}<Input form={form} id="detail-capacity" label="Cupo máximo de niños" name="capacity" type="number" /></> : <p className="text-sm text-muted-foreground sm:col-span-2">Solo un administrador puede modificar ciclo, profesor, horario o cupo.</p>}<div className="sm:col-span-2"><Button disabled={pending} type="submit">{pending ? "Guardando…" : "Guardar cambios"}</Button></div></form> : null}</div>;
}
function Input({ form, id, label, name, type = "text" }: { form: UseFormReturn<ClassValues>; id: string; label: string; name: keyof ClassValues; type?: string }) { const error = form.formState.errors[name]; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor={id}>{label}</label><input className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id={id} type={type} {...form.register(name, type === "number" ? { valueAsNumber: true } : undefined)} />{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
function TeacherSelect({ form, teachers }: { form: UseFormReturn<ClassValues>; teachers: { id: string; name: string }[] }) { const error = form.formState.errors.teacherId; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor="detail-teacher">Profesor</label><select className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id="detail-teacher" {...form.register("teacherId")}><option value="">Selecciona una opción</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select>{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
function CycleSelect({ cycles, form }: { cycles: { id: string; name: string }[]; form: UseFormReturn<ClassValues> }) { const error = form.formState.errors.cycleId; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor="detail-cycle">Ciclo</label><select className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id="detail-cycle" {...form.register("cycleId")}><option value="">Selecciona una opción</option>{cycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{cycle.name}</option>)}</select>{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
function DateInput({ form, id, label, max, min, name }: { form: UseFormReturn<ClassValues>; id: string; label: string; max?: string; min?: string; name: "startsAt" | "endsAt" }) { const error = form.formState.errors[name]; return <div className="space-y-2"><label className="text-sm font-medium" htmlFor={id}>{label}</label><input className="h-10 w-full rounded-lg border bg-background px-3 text-sm" id={id} max={max} min={min} type="datetime-local" {...form.register(name)} />{error ? <p className="text-sm text-destructive" role="alert">{error.message}</p> : null}</div>; }
